# Generated by Django 4.2.20 on 2025-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_heading_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
