# Generated by Django 4.2.20 on 2025-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='paragraph_text',
            field=models.TextField(default='Welcome to our website!', help_text='Edit this text from the Wagtail admin panel.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Soluciones integrales en tecnología', max_length=255),
        ),
    ]
