# Generated by Django 4.2.20 on 2025-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_paragraph_text_alter_homepage_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='paragraph_text',
            field=models.TextField(default='Calidad y experiencia en servicios', help_text='Edit this text from the Wagtail admin panel.'),
        ),
    ]
