# Generated by Django 4.2.19 on 2025-03-10 14:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_homepage_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cards2",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("imagex", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cards3",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("imagex", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
