# Generated by Django 4.2.19 on 2025-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_carouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
