# Generated by Django 4.2.19 on 2025-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_carouselimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="address",
            field=models.CharField(default="Calle Ejemplo #123", max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="city",
            field=models.CharField(default="La Paz", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="country",
            field=models.CharField(default="Bolivia", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="email",
            field=models.EmailField(default="contacto@tuempresa.com", max_length=254),
        ),
        migrations.AddField(
            model_name="homepage",
            name="facebook_url",
            field=models.URLField(
                blank=True, help_text="Enlace a tu página de Facebook"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="Enlace a tu perfil o empresa en LinkedIn"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="phone",
            field=models.CharField(default="+591 700-00000", max_length=20),
        ),
        migrations.AddField(
            model_name="homepage",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Número de WhatsApp con código de país",
                max_length=20,
            ),
        ),
    ]
