# Generated by Django 4.2.19 on 2025-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_homepage_address_homepage_city_homepage_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="whatsapp_number",
            field=models.URLField(
                blank=True, help_text="Número de WhatsApp con código de país"
            ),
        ),
    ]
