# Generated by Django 4.2.20 on 2025-03-18 11:33

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='caption',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
