# Generated by Django 4.2.20 on 2025-03-18 11:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_carouselimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'embed', 'image', 'table'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('imagex', 0), ('title', 1), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cards2',
            field=wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'embed', 'image', 'table'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('imagex', 0), ('title', 1), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cards3',
            field=wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'embed', 'image', 'table'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('imagex', 0), ('title', 1), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='paragraph_text',
            field=wagtail.fields.RichTextField(default='Calidad y experiencia en servicios', help_text='Edit this text from the Wagtail admin panel.'),
        ),
    ]
