# Generated by Django 4.2.20 on 2025-03-18 20:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_carouselimage_font_color_alter_homepage_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards2',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'embed', 'image', 'table', 'color', 'colorpicker'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('imagex', 0), ('title', 1), ('description', 2)]], {})}),
        ),
    ]
