# Generated by Django 4.2.20 on 2025-03-21 15:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_homepage_cards2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="paragraph_text",
            new_name="seccion1",
        ),
        migrations.AddField(
            model_name="homepage",
            name="seccion2",
            field=wagtail.fields.RichTextField(
                default="Calidad y experiencia en servicios",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seccion3",
            field=wagtail.fields.RichTextField(
                default="Calidad y experiencia en servicios",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="heading",
            field=wagtail.fields.RichTextField(
                default="Calidad y experiencia en servicios",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
    ]
