# Generated by Django 4.2.20 on 2025-03-21 19:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0021_alter_homepage_seccion1_alter_homepage_seccion2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="p1",
            field=wagtail.fields.RichTextField(
                default="ELECTROMECANICA",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="p2",
            field=wagtail.fields.RichTextField(
                default="MANTENIMIENTO INDUSTRIAL",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="p3",
            field=wagtail.fields.RichTextField(
                default="SISTEMAS DE SEGURIDAD",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
    ]
