# Generated by Django 4.2.20 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_homepage_banner_homepage_p1_homepage_p2_homepage_p3"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_color_ban",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="font_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="font_color2",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
