# Generated by Django 4.2.20 on 2025-03-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0024_alter_homepage_cards_alter_homepage_cards2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="font_color2",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo Teravolt",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="image1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Seccion 1",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="image2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Seccion 2",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="image3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Seccion 3",
            ),
        ),
    ]
