# Generated by Django 4.2.20 on 2025-03-24 20:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0025_remove_homepage_font_color2_alter_homepage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="backS1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="background Seccion 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="backS2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="background Seccion 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="backS3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="background Seccion 3",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_b1",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_b2",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_b3",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_s1",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_s2",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_s3",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerMV",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Vision Mision",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerS1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Seccion 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerS2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Seccion 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerS3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Seccion 3",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pMV1",
            field=wagtail.fields.RichTextField(
                default="mision",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pMV2",
            field=wagtail.fields.RichTextField(
                default="vision",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pOB",
            field=wagtail.fields.RichTextField(
                default="objetivos",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pQS",
            field=wagtail.fields.RichTextField(
                default="Quienes somos",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
    ]
