# Generated by Django 4.2.20 on 2025-04-01 23:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("home", "0026_homepage_backs1_homepage_backs2_homepage_backs3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="background_color",
            new_name="background_color_bC",
        ),
        migrations.AddField(
            model_name="homepage",
            name="MV_colorback",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                verbose_name="Color de fondo titulo seccion",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="backSC",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="background Seccion Cliente",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_color_sC",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerMV_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                verbose_name="Color fondo de Mision Vision",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerMsec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division seccion Vision Mision",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bannerSC",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Seccion Cliente",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="fontMV",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="homepage",
            name="font_color_secciones",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="Color titulo Secciones"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pCliente",
            field=wagtail.fields.RichTextField(
                default="SISTEMAS DE SEGURIDAD",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pMVT",
            field=wagtail.fields.RichTextField(
                default="Mision Vision",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seccionCliente",
            field=wagtail.fields.RichTextField(
                default="Clientes",
                help_text="Edit this text from the Wagtail admin panel.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="bannerMV",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen Division Mision Vision",
            ),
        ),
        migrations.CreateModel(
            name="SectionG",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", wagtail.fields.RichTextField()),
                ("caption", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "font_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color del texto de la descripción",
                    ),
                ),
                (
                    "font_color2",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Color del título"
                    ),
                ),
                (
                    "backcolor",
                    models.CharField(
                        default="#ffffff",
                        max_length=7,
                        verbose_name="Transparencia de la seccion",
                    ),
                ),
                (
                    "backcontent_color",
                    models.CharField(
                        default="#ffffff",
                        max_length=7,
                        verbose_name="Transparencia de la seccion",
                    ),
                ),
                (
                    "backcontent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen seccion",
                    ),
                ),
                (
                    "backimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen division seccion",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsG",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", wagtail.fields.RichTextField(verbose_name="Titulo")),
                (
                    "caption",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Descripcion"
                    ),
                ),
                (
                    "font_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color descripcion",
                    ),
                ),
                (
                    "font_color2",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Color titulo"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="ID del target de la imagen",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secciones",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.CreateModel(
            name="ClientslImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_clients",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen del Carrusel",
                "verbose_name_plural": "Imágenes del Carrusel",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", wagtail.fields.RichTextField()),
                ("description", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "font_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color del texto de la descripción",
                    ),
                ),
                (
                    "font_color2",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color del texto del titulo",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardsgeneral",
                        to="home.sectiong",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
            },
        ),
    ]
